[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip", "postgresql.dev", "libpq"]

[phases.install]
cmds = [
    "cd frontend && npm install --legacy-peer-deps",
    "cd backend && pip install -r requirements.txt --break-system-packages"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "cd backend && echo 'Backend ready'"
]

[start]
cmd = "cd backend && python src/main.py"
