[phases.setup]
nixPkgs = ['nodejs', 'python311', 'python311Packages.pip', 'python311Packages.virtualenv', 'postgresql']

[phases.install]
cmds = [
    'cd frontend && npm install --legacy-peer-deps',
    'cd backend && python -m venv venv',
    'cd backend && source venv/bin/activate && pip install --upgrade pip setuptools wheel',
    'cd backend && source venv/bin/activate && pip install -r requirements.txt --no-cache-dir'
]

[phases.build]
cmds = [
    'cd frontend && npm run build',
    'cd backend && echo "Backend ready"'
]

[start]
cmd = 'cd backend && source venv/bin/activate && python src/main.py'